buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        mavenLocal()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.1'
    }
}

apply plugin: 'com.android.application'

android {
    namespace 'com.isfs.blekey' 

    compileSdkVersion 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }


    defaultConfig {
        applicationId "com.isfs.blekey"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        debug {
            minifyEnabled false
            debuggable true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    packaging {
        resources.excludes.add("META-INF/versions/9/OSGI-INF/MANIFEST.MF")
        resources.excludes.add("META-INF/NOTICE.md")
        resources.excludes.add("META-INF/LICENSE.md")
    }
}



configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'org.jetbrains.kotlin') {
            details.useVersion '1.8.22'
        }
    }
}

repositories {
    google()
    mavenCentral()
    maven { url 'https://jitpack.io' }
    mavenLocal()
}


dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.annotation:annotation:1.0.2'
    implementation 'org.slf4j:slf4j-api:1.7.30'
    implementation 'androidx.core:core:1.12.0'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'com.github.tony19:logback-android:3.0.0'
    implementation 'no.nordicsemi.android:ble:2.6.1'
    implementation 'isfs:com.isfs.blekey.common:0.00.10'

}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

task wrapper(type: Wrapper){
   gradleVersion = '8.1.1'
}

