// Assisted by watsonx Code Assistant 
// Code generated by WCA@IBM in this programming language is not approved for use in IBM product development.


package com.example.blehidfido2.logging;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class LogbackAndroid {
    private static final Logger logger = LoggerFactory.getLogger(LogbackAndroid.class);

    public static void init() {
        logger.debug("LogbackAndroid initialized");
    }

    public static Logger getLogger() {
        return logger;
    }
}

