// Assisted by watsonx Code Assistant 
// Code generated by WCA@IBM in this programming language is not approved for use in IBM product development.

package com.example.blehidfido2.logging;

import android.util.Log;
import ch.qos.logback.classic.encoder.PatternLayoutEncoder;

public class LogbackLayout extends PatternLayoutEncoder {
    public LogbackLayout() {
        setContext(LogbackAndroid.getContext());
        setPattern("%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n");
    }

    @Override
    public void start() {
        super.start();
        setAndroidLogFormatter();
    }

    private void setAndroidLogFormatter() {
        setContext(LogbackAndroid.getContext());
        setContext(new android.util.Log.ThreadInfo(Log.DEBUG, "Fido2Peripheral"));
        setContext(new android.util.Log.ThreadInfo(Log.DEBUG, "CtapHid"));
    }
}